---
application:
  name: "node-app"
  project: "environment-variables-demo"
  organization: "QoveryCommunity"
routers:
- name: "main-node-app"
  routes:
  - application_name: "node-app"
    paths:
    - "/*"
